spring.application.name=careeros
spring.datasource.url=jdbc:postgresql://localhost:5432/careeros_db
spring.datasource.username=postgres
spring.datasource.password=yein060131@

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
